# Generated by Django 5.1.2 on 2024-11-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
