# Generated by Django 5.1.2 on 2024-11-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_event_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
